application:
  host: "127.0.0.1"
  port: 3000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "gritwit"
  require_ssl: false
  channel_binding: false
oauth:
  google_client_id: "PLACEHOLDER"
  google_client_secret: "PLACEHOLDER"
  redirect_url: "http://localhost:3000/auth/google/callback"
